const language = [
    {
        "legend": "Legend",
        "noCase": "No Case",
        "stayHome": "StayHome",
        "total": "Total",
        "cases": "Cases",
        "deaths": "Deaths",
        "recovered": "Recovered",
        "notation": "Map Notation",
        "area": "Area",
        "circle": "Circle",
        "dayRange": "Timer is loading...",
        "countryName": "Country name...",
        "detailInfo": "Click for details...",
        "active": "Active:",
        "todayDeaths": "Today Death:",
        "critical": "Critical:",
        "todayCases": "Today Cases:",
        "casesPerOneMillion": "Cases Per One Million:",
        "deathsPerOneMillion": "Deaths Per One Million:",
        "totalTests": "Total Test:",
        "testsPerOneMillion": "Tests Per One Million:",
        "graphics": "Graphics",
        "general": "General",
        "dailyCase": "Daily Case",
        "dailyDeaths": "Daily Deaths",
        "dailyRecovered": "Daily Recovered",
        "selectCompare": "Select the country you want to compare.",
        "graphicProvider": "Graphic Data Provider:",
        "connectionError": "Failed to connect to data provider.",
        "generalStatus": "General Status",
        "comparativeTotal": "Comparative Total",
        "remove": "Remove",
        "noDataSelected": "No data was found for selected country.",
        "newCases": "New Cases",
        "announcedCase": "announced new cases.",
        "announcedDeaths": "announced new deaths.",
        "announcedRecovered": "announced new recovered cases.",
        "newCount": "New count:"
    },
    {
        "legend": "Lejant",
        "noCase": "Vaka Yok",
        "stayHome": "EvdeKal",
        "total": "Toplam",
        "cases": "Vaka",
        "deaths": "Ölüm",
        "recovered": "İyileşen",
        "notation": "Harita Gösterimi",
        "area": "Alan",
        "circle": "Daire",
        "dayRange": "Zamanlayıcı yükleniyor...",
        "countryName": "Ülke adı...",
        "detailInfo": "Detay için tıklayınız...",
        "active": "Aktif:",
        "todayDeaths": "Bugünkü Ölümler:",
        "critical": "Durumu Kritik:",
        "todayCases": "Bugünkü Vakalar:",
        "casesPerOneMillion": "Bir Milyonda Vaka:",
        "deathsPerOneMillion": "Bir Milyonda Ölüm:",
        "totalTests": "Toplam Test:",
        "testsPerOneMillion": "Bir Milyonda Test:",
        "graphics": "Grafikler",
        "general": "Genel",
        "dailyCase": "Günlük Vaka",
        "dailyDeaths": "Günlük Ölüm",
        "dailyRecovered": "Günlük İyileşme",
        "selectCompare": "Karşılaştırma yapmak istediğiniz ülkeyi seçiniz.",
        "graphicProvider": "Grafik Veri Sağlayıcısı:",
        "connectionError": "Veri sağlayıcısına bağlanılamadı.",
        "generalStatus": "Genel Durum",
        "comparativeTotal": "Karşılaştırmalı Toplam",
        "remove": "Kaldır",
        "noDataSelected": "Seçtiğiniz ülkeye ait veri bulunamadı.",
        "newCases": "Yeni Vakalar",
        "announcedCase": "yeni vakalar açıkladı",
        "announcedDeaths": "yeni kayıplar açıkladı.",
        "announcedRecovered": "yeni iyileşen vakalar açıkaldı.",
        "newCount": "Yeni sayı:"
    }
]

export default language; 